### ISSUE TITLE
Expression is always true AStar.cs line 56

### ISSUE THREAD

**Issue by ghost** [kingcoyote/algorithms_csharp#1]
```
while (prev != null)
{
 path.Push(prev.Node);
 prev = prev.Previous;
 }
```
In this case, the condition will always be true

**Comment by kingcoyote** [comment]
Not always. There might be some edge case where this is possible, but if this were always true then GeneratePath would never return a path, and I've been using this code successfully for years. It should eventually return the node created on line 11, which is the start node.

If it never returns that node, then somehow the AStarPQNode has gone in a circle. If you can post code that reliably reproduces that, we can figure it out.
